[package]
name = "matset"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.217", default-features = false, features = ["derive", "alloc"] }
serde_json = { version = "1.0.138", default-features = false, features = ["alloc"] }
wasm-minimal-protocol = "0.1.0"
