[package]
name = "matset"
version = "0.1.0"
entrypoint = "api.typ"
authors = ["@OptimisticPeach", "patrikbuhring@gmail.com"]
license = "MIT"
description = "An ergonomic expression evaluator in Typst"

